### ISSUE TITLE
playback fails with 403

### ISSUE THREAD

**Issue by sourcejedi** [kozec/chrome-extension-daisuki-html5#1]
Sadly for me this extension didn't work either. (Is there any reference to why the Flash stopped working? I've been assuming it's a Linux thing, but this extension is the first place I've found _anyone_ else talk about the "not working Flash player").

URL tested: http://www.daisuki.net/gb/en/anime/watch.TalesofZestiriatheX.13476.html

Error in browser console: granite.min.js:64 GET https://bngn-vh.akamaihd.net/i/43383936/35470338/smil/SK/00039/236341282358…l=/*~hmac=9df9e96d88252edb6c5bf0327a17d90d692725f7a4f988e70b31255fb4493ce1 403 (Forbidden)

In Network Console, "Preview" tab shows: You don't have permission to access "http://bngn-vh.akamaihd.net/i/43383936/35470338/smil/SK/00039/236341282358037.smil/master.m3u8?" on this server.

**Comment by sourcejedi** [comment]
(So I should have said: Thanks for posting the extension.  Whether this is fixable or not)

**Comment by kozec** [comment]
Ah, yeah. You are probably hitting region lock with this :(

Are you installing from source or from Web Store? Basically, problem is with that SK in that 2nd url, so changing it to GB or detecting correct country may help, but I have no way how to test it from here.

**Comment by sourcejedi** [comment]
Ah. good catch! I used Web Store, but should be able to test github versions easily enough. You're right that substituting GB for SK in the url fixes the 403, so hopefully it's as simple as that. I may be too lazy to fix the source though. Looks like the country code could be scraped from the page URL if nowhere else, just need to make it upper-case.

**Comment by kozec** [comment]
^^ this should basically fix it, but it would help if you could test it and confirm it works. I tested it only using some weird proxy extension, so I'm not 100% sure.

**Comment by sourcejedi** [comment]
Yosh!

(How could I possibly have installed from source alone, you tease, it seems to be missing certain critical files :-)

So that gets past the region-blocking, thanks!

Then I seem to have idiographic subtitles. Actually, I seem to have _all_ the subtitles - I saw it switching between ideographs, English, and Spanish. And something that looks like Thai.

The subtitle menu shows only English :). I can switch subtitles off entirely, but switching back to "English" subtitles still gives me all the languages at once.

**Comment by kozec** [comment]
> (How could I possibly have installed from source alone, you tease, it seems to be missing certain critical files :-)

Just default flowplayer installation that I'd rather not have included in source because of their license.

> Then I seem to have idiographic subtitles. Actually, I seem to have all the subtitles - I saw it switching between ideographs, English, and Spanish. And something that looks like Thai.

I didn't even knew that Daisuki knows about other languages, but I can check why it's happening.
Which show and which episode does that?

**Comment by sourcejedi** [comment]
icon*.png are missing too.

Sorry, I should have said - this time I just clicked through the show promoted on the frontpage.  To this URL:
http://www.daisuki.net/gb/en/anime/watch.TalesofZestiriatheX.13476.html

**Comment by kozec** [comment]
Version in chrome store is updated as well, but currently it is waiting for approval.
