### ISSUE TITLE
Subtitles only working one time

### ISSUE THREAD

**Issue by SonGokuSSJ** [kozec/chrome-extension-daisuki-html5#2]
I use this neat little extension to watch dragon ball super, but got a problem with the subtitles. After installing this extension it works fine, but all later watches do not show the subtitles. Disabling and re-enabling do not help. I have to remove the extension and install it again. It works then again for only on episode.

This happens to me on both Vivaldi (64 Bit) and Chrome (32 Bit).

**Comment by kozec** [comment]
Weird, it seems working for me. Can you check if there is any error displayed in developer console (F12) while video is playing?

**Comment by SonGokuSSJ** [comment]
Dear kozec,

thank you for the answer. Yes, it shows 10 errors and 67 (or so) warnings.

[www.daisuki.net-1480370293708.txt](https://github.com/kozec/chrome-extension-daisuki-html5/files/617617/www.daisuki.net-1480370293708.txt)

**Comment by kozec** [comment]
Ok, so domain from which subtitles are served changed. I know what to do, but it will take some time - I'm not at my PC right now and google web store takes hours before update is published.

**Comment by SonGokuSSJ** [comment]
Thank you for your investigation / analysis. That's no problem if it takes some time. I am just glad that the problem will be solved in the future.

**Comment by kozec** [comment]
So, this was practically unfixable for so long, so someone else fixed it for me :)

Daisuki's subtitle servers started to using `access-control-allow-origin:http://www.daisuki.net` header, what solves everything, even for extension code as it is. I'll remove that bugged workaround and update extension anyway, but no fix is needed to watch subtitles now.

**Comment by SonGokuSSJ** [comment]
Thank you, it works now.

**Comment by Darksouls04** [comment]
Canyo u add an option to select resolution?
