### ISSUE TITLE
Flash Player does not get replaced.

### ISSUE THREAD

**Issue by SonGokuSSJ** [kozec/chrome-extension-daisuki-html5#5]
daisuki has ended most of its service in the last months and is now only streaming dragon ball super. But with that they changed the url to http://motto.daisuki.net/information and the video urls now look like http://motto.daisuki.net/framewatch/embed/embedDRAGONBALLSUPERUniverseSurvivalsaga/P2e/760/428 . But the Flash Player does not get replaced anymore.

**Comment by kozec** [comment]
There is good chance that changing domains in [manifest](https://github.com/kozec/chrome-extension-daisuki-html5/blob/master/manifest.json#L15) will fix this, but  they region-locked my country so I can't really debug it... I wasn't even aware they didn't removed everything.

I should probably remove this thing at least from google store. Sorry about that.

**Comment by SonGokuSSJ** [comment]
That's bad that they geolocked you. This morning it was also not working for me (the flash player wouldn't load), but this evening I switched computers and atleast the flash version is working. 

I changed the url in manifest.json, but that did not help. I found www.daisuki.net in page.js ( $.get("http://www.daisuki.net" + flashvars['init'], params, function(data) { ) and switched that also to motto.daisuki.net, but that did not help either. Maybe they have changed even more. 

But this extension is not the only one with problems. youtube-dl also does not work with the new urls, so I created a bug report there also.

**Comment by henrymai** [comment]
Updated extension here:
https://github.com/henrymai/chrome-extension-daisuki-html5

You can just download the entire repository as a zip, extract it to a folder, then load it into chrome (enable developer mode -> load unpacked extension).

edit: Ignore my previous note about it not working for anything other than the latest episode, I just force pushed a replacement commit that makes it work completely without hacks. I will also send a pull request soon.

**Comment by henrymai** [comment]
Just sent the pull request: https://github.com/kozec/chrome-extension-daisuki-html5/pull/6

**Comment by SonGokuSSJ** [comment]
Thank you very much for taking a look into it. I will try it as soon as I can (probably tomorrow, if not then at the weekend).

**Comment by SonGokuSSJ** [comment]
I just had time and can confirm, that it is working. Thank you very much for your effort.

**Comment by SonGokuSSJ** [comment]
Today I tried it on another computer and am getting now the following message:

"html5: Unsupported video format. Try installing Adobe Flash."

Edit: OK, installed flash and it is working. But shouldn't it work without flash? I thought it would replace flash with html5.

**Comment by kozec** [comment]
> "html5: Unsupported video format. Try installing Adobe Flash."

That's flowplayer message and it can really mean that daisuki really used format or codec that browser can't handle by itself.

But I saw it few times back when normal site worked and just refreshing always helped.

**Comment by henrymai** [comment]
You shouldn't need flash installed, you just need to refresh the page a couple of times when you see that message.

**Comment by henrymai** [comment]
Also I find that if refreshing doesn't help, closing the tab and reopening another tab with daisuki helps.

**Comment by SonGokuSSJ** [comment]
Thank you, refreshing (more often) does indeed help.

**Comment by SonGokuSSJ** [comment]
Closing the issue now as it is working really fine. Thank you for the help and for updating the extension.

**Comment by SonGokuSSJ** [comment]
From my view you can add the extension back to the chrome store.
